name: Test push to main tier0

on:
    push:
        branches:
            - main

concurrency:
    group: tier0-push-main-${{ github.ref }}
    cancel-in-progress: true

jobs:
    main-tier0:
        uses: ./.github/workflows/run-ui-tests.yaml
        with:
            test_spec: "cypress/e2e/tests/{ci,tier0}/**/*.test.ts"
            feature_auth_required: true
            bundle_image: quay.io/konveyor/tackle2-operator-bundle:latest
            install_konveyor_version: main
            test_ref: main
